[package]
name = "ormlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datetime = "0.5.2"
sqlx = { version = "0.5.9", features = ["runtime-actix-native-tls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
