[workspace]
members = ["ormlite-macro", "ormlite-core", "ormlite-core", "ormlite-bench", "ormlite"]

[patch.crates-io]
ormlite-macro = { path = "./ormlite-macro" }
ormlite-core = { path = "./ormlite-core" }
