[package]
name = "ormlite"
version = "0.1.3"
edition = "2021"
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
description = "An ORM for people who love SQL"
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"
autotests = false
readme = "../README.md"

[package.metadata.docs.rs]
features = ["sqlite", "runtime-tokio-rustls"]

[[test]]
name = "tests"
path = "tests/suite.rs"

[dependencies]
ormlite-macro = "0.1.0"
ormlite-core = "0.1.0"
sqlx = "0.5.9"
tokio = { version = "1.15.0", features = ["full"] }
env_logger = {version = "0.9.0", optional = true}

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }

[features]
mysql = ["sqlx/mysql", "ormlite-macro/mysql"]
sqlite = ["sqlx/sqlite", "ormlite-macro/sqlite", "ormlite-core/sqlite"]
postgres = ["sqlx/postgres", "ormlite-macro/postgres", "ormlite-core/postgres"]
# enables the `handwritten` module, which is a manual implementation of what the macros produce, for dev/test/benchmarking
handwritten = ["env_logger"]

runtime-tokio-rustls = ["ormlite-macro/runtime-tokio-rustls", "sqlx/runtime-tokio-rustls", "ormlite-core/runtime-tokio-rustls"]
insert = []
