[package]
name = "ormlite"
version = "0.2.1"
edition = "2021"
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
description = "An ORM for people who love SQL"
license = "MIT"
repository = "https://github.com/kurtbuilds/ormlite"
autotests = false
readme = "../README.md"

[package.metadata.docs.rs]
features = ["sqlite", "postgres", "runtime-tokio-rustls"]

lib = ["lib.rs"]

[[test]]
name = "tests"
path = "tests/suite.rs"

[features]
mysql = ["sqlx/mysql", "ormlite-macro/mysql"]
sqlite = ["sqlx/sqlite", "ormlite-macro/sqlite", "ormlite-core/sqlite"]
postgres = ["sqlx/postgres", "ormlite-macro/postgres", "ormlite-core/postgres"]
runtime-tokio-rustls = ["ormlite-macro/runtime-tokio-rustls", "sqlx/runtime-tokio-rustls", "ormlite-core/runtime-tokio-rustls"]

[dependencies]
ormlite-macro = "0.2.0"
ormlite-core = "0.2.0"
sqlx = { version = "0.5.13", features = ["uuid"] }
tokio = { version = "1.15.0", features = ["full"] }
uuid = { version = "1.0.0", optional = true }

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }
env_logger = "0.9.0"

[patch.crates-io]
ormlite-core = { path = "../ormlite-core" }
ormlite-macro = { path = "../ormlite-macro" }
