[package]
name = "ormlite-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
bench = ["criterion", "sea-orm", "ormx", "anyhow", "rusqlite", "diesel"]

#[[bench]]
#name = "leaderboard"
#harness = false
